name: Env Vars

on: workflow_dispatch

jobs:
  foobar:
    runs-on: ubuntu-latest

    env:
      BUILD_TIME: ${{github.event.repository.updated_at}}
      BUILD_VERSION: ${{env.GITHUB_SHA}}

    steps:
      - name: "Build Time"
        run: "echo ${{ env.BUILD_TIME }}" 
      - name: "Build Version"
        run: "echo ${{ env.BUILD_VERSION }}"
